"""Retro pixel-art sprites + large PNG asset paths for the study sticker."""

from __future__ import annotations

from pathlib import Path

from tracker.paths import PROJECT_ROOT, STICKERS_DIR

ROOT = PROJECT_ROOT
ASSETS_DIR = STICKERS_DIR
PIXEL = 3
DISPLAY_SCALE = 12  # matches generate_sticker_assets EXPORT_SCALE

PALETTES = {
    "vader": {
        ".": "",
        "K": "#050505",
        "k": "#1a1a1a",
        "H": "#3f3f46",
        "h": "#52525b",
        "G": "#27272a",
        "R": "#dc2626",
        "r": "#fca5a5",
        "W": "#71717a",
    },
    "yoda": {
        ".": "",
        "K": "#3f6212",
        "k": "#4d7c0f",
        "G": "#65a30d",
        "g": "#84cc16",
        "Y": "#bef264",
        "y": "#ecfccb",
        "B": "#713f12",
        "b": "#a16207",
        "S": "#22c55e",
        "s": "#4ade80",
    },
    "mando": {
        ".": "",
        "K": "#0f172a",
        "k": "#1e293b",
        "S": "#64748b",
        "s": "#94a3b8",
        "H": "#cbd5e1",
        "B": "#38bdf8",
        "b": "#7dd3fc",
        "G": "#334155",
        "R": "#475569",
    },
    "dooku": {
        ".": "",
        "W": "#fafaf9",
        "w": "#e7e5e4",
        "K": "#1c1917",
        "k": "#292524",
        "G": "#44403c",
        "P": "#a8a29e",
        "R": "#ef4444",
        "r": "#fecaca",
        "B": "#7c2d12",
    },
}

SPRITES = {
    "vader": [
        [
            "......kkkk......",
            ".....kKKKKk.....",
            "....kKKHHKKk....",
            "...kKKKRRKKKk...",
            "...kKKKRRKKKk...",
            "....kKKKKKKk....",
            ".....kKKKKk.....",
            "......kKKk......",
            ".....kGGGGk.....",
            "....kGGWWGGk....",
            "...kGGWWWWGGk...",
            "...kGGWWWWGGk...",
            "...kGGWWWWGGk...",
            "....kGGGGGGk....",
            ".....kGGGGk.....",
            "......kGGk......",
            ".......kk.......",
            ".......RR.......",
            "......RRrR......",
            ".....RRrRR......",
            "....RRrRRr......",
            ".....RRrR.......",
            "......RR........",
            ".......r........",
        ],
        [
            "......kkkk......",
            ".....kKKKKk.....",
            "....kKKHHKKk....",
            "...kKKKRRKKKk...",
            "...kKKKRRKKKk...",
            "....kKKKKKKk....",
            ".....kKKKKk.....",
            "......kKKk......",
            ".....kGGGGk.....",
            "....kGGWWGGk....",
            "...kGGWWWWGGk...",
            "...kGGWWWWGGk...",
            "...kGGWWWWGGk...",
            "....kGGGGGGk....",
            ".....kGGGGk.....",
            "......kGGk......",
            ".......kk.......",
            "........RR......",
            ".......RRrR.....",
            "......RRrRR.....",
            ".....RRrRRrR....",
            "......RRrRR.....",
            ".......RRr......",
            "........r.......",
        ],
        [
            "......kkkk......",
            ".....kKKKKk.....",
            "....kKKHHKKk....",
            "...kKKKRRKKKk...",
            "...kKKKRRKKKk...",
            "....kKKKKKKk....",
            ".....kKKKKk.....",
            "......kKKk......",
            ".....kGGGGk.....",
            "....kGGWWGGk....",
            "...kGGWWWWGGk...",
            "...kGGWWWWGGk...",
            "...kGGWWWWGGk...",
            "....kGGGGGGk....",
            ".....kGGGGk.....",
            "......kGGk......",
            ".......kk.......",
            ".....RRrRR......",
            "....RRrRRr......",
            "...RRrRRrRR.....",
            "....RRrRRr......",
            ".....RRrR.......",
            "......RR........",
            ".......r........",
        ],
        [
            "......kkkk......",
            ".....kKKKKk.....",
            "....kKKHHKKk....",
            "...kKKKRRKKKk...",
            "...kKKKRRKKKk...",
            "....kKKKKKKk....",
            ".....kKKKKk.....",
            "......kKKk......",
            ".....kGGGGk.....",
            "....kGGWWGGk....",
            "...kGGWWWWGGk...",
            "...kGGWWWWGGk...",
            "...kGGWWWWGGk...",
            "....kGGGGGGk....",
            ".....kGGGGk.....",
            "......kGGk......",
            ".......kk.......",
            ".......RR.......",
            "......RRrR......",
            ".....RRrRR......",
            "....RRrRRr......",
            ".....RRrR.......",
            "......RR........",
            ".......r........",
        ],
    ],
    "yoda": [
        [
            "......kkkk......",
            ".....kGGGGk.....",
            "...kkGGYYGGkk...",
            "..kGGGYYYYGGGk..",
            ".kGGGYYYYYYGGGk.",
            ".kGGGYYYYYYGGGk.",
            "..kGGGYYYYGGGk..",
            "...kkGGYYGGkk...",
            ".....kGGGGk.....",
            "......kGGk......",
            ".....kBBBBk.....",
            "....kBBBBBBk....",
            "...kBBBBBBBBk...",
            "...kBBBBBBBBk...",
            "....kBBBBBBk....",
            ".....kBBBBk.....",
            "......kBBk......",
            ".......SS.......",
            "......SsS.......",
            ".....SsSSS......",
            "......SsS.......",
            ".......S........",
        ],
        [
            "......kkkk......",
            ".....kGGGGk.....",
            "...kkGGYYGGkk...",
            "..kGGGYYYYGGGk..",
            ".kGGGYYYYYYGGGk.",
            ".kGGGYYYYYYGGGk.",
            "..kGGGYYYYGGGk..",
            "...kkGGYYGGkk...",
            ".....kGGGGk.....",
            "......kGGk......",
            ".....kBBBBk.....",
            "....kBBBBBBk....",
            "...kBBBBBBBBk...",
            "...kBBBBBBBBk...",
            "....kBBBBBBk....",
            ".....kBBBBk.....",
            "......kBBk......",
            ".....SsSSS......",
            "....SsSSSSS.....",
            "...SsSSSSSSS....",
            "....SsSSSSS.....",
            ".....SsSSS......",
        ],
        [
            "......kkkk......",
            ".....kGGGGk.....",
            "...kkGGYYGGkk...",
            "..kGGGYYYYGGGk..",
            ".kGGGYYYYYYGGGk.",
            ".kGGGYYYYYYGGGk.",
            "..kGGGYYYYGGGk..",
            "...kkGGYYGGkk...",
            ".....kGGGGk.....",
            "......kGGk......",
            ".....kBBBBk.....",
            "....kBBBBBBk....",
            "...kBBBBBBBBk...",
            "...kBBBBBBBBk...",
            "....kBBBBBBk....",
            ".....kBBBBk.....",
            "......kBBk......",
            ".......SS.......",
            "......SsS.......",
            ".....SsSSS......",
            "......SsS.......",
            ".......S........",
        ],
        [
            "......kkkk......",
            ".....kGGGGk.....",
            "...kkGGYYGGkk...",
            "..kGGGYYYYGGGk..",
            ".kGGGYYYYYYGGGk.",
            ".kGGGYYYYYYGGGk.",
            "..kGGGYYYYGGGk..",
            "...kkGGYYGGkk...",
            ".....kGGGGk.....",
            "......kGGk......",
            ".....kBBBBk.....",
            "....kBBBBBBk....",
            "...kBBBBBBBBk...",
            "...kBBBBBBBBk...",
            "....kBBBBBBk....",
            ".....kBBBBk.....",
            "......kBBk......",
            ".......sS.......",
            "......sSSS......",
            ".....sSSSSS.....",
            "......sSSS......",
            ".......s........",
        ],
    ],
    "mando": [
        [
            "......SSSS......",
            ".....SSHHSS.....",
            "....SSHHHHSS....",
            "...SSSHBBBSSS...",
            "...SSSHBBBSSS...",
            "...SSSHBBBSSS...",
            "...SSSHBBBSSS...",
            "....SSHHHHSS....",
            ".....SSHHSS.....",
            "......SSSS......",
            ".....kGGGGk.....",
            "....kGGGGGGk....",
            "...kGGGGGGGGk...",
            "...kGGGGGGGGk...",
            "....kGGGGGGk....",
            ".....kGGGGk.....",
            "......kGGk......",
            ".......BB.......",
            "......BBBB......",
            ".....BBBBBB.....",
            "......BBBB......",
            ".......BB.......",
        ],
        [
            "......SSSS......",
            ".....SSHHSS.....",
            "....SSHHHHSS....",
            "...SSSHBBBSSS...",
            "...SSSHBBBSSS...",
            "...SSSHBBBSSS...",
            "...SSSHBBBSSS...",
            "....SSHHHHSS....",
            ".....SSHHSS.....",
            "......SSSS......",
            ".....kGGGGk.....",
            "....kGGGGGGk....",
            "...kGGGGGGGGk...",
            "...kGGGGGGGGk...",
            "....kGGGGGGk....",
            ".....kGGGGk.....",
            "......kGGk......",
            "......BBBBB.....",
            ".....BBBBBBB....",
            "....BBBBBBBBB...",
            ".....BBBBBBB....",
            "......BBBBB.....",
        ],
        [
            "......SSSS......",
            ".....SSHHSS.....",
            "....SSHHHHSS....",
            "...SSSHBBBSSS...",
            "...SSSHBBBSSS...",
            "...SSSHBBBSSS...",
            "...SSSHBBBSSS...",
            "....SSHHHHSS....",
            ".....SSHHSS.....",
            "......SSSS......",
            ".....kGGGGk.....",
            "....kGGGGGGk....",
            "...kGGGGGGGGk...",
            "...kGGGGGGGGk...",
            "....kGGGGGGk....",
            ".....kGGGGk.....",
            "......kGGk......",
            ".......BB.......",
            "......BBBB......",
            ".....BBBBBB.....",
            "......BBBB......",
            ".......BB.......",
        ],
        [
            "......SSSS......",
            ".....SSHHSS.....",
            "....SSHHHHSS....",
            "...SSSHBBBSSS...",
            "...SSSHBBBSSS...",
            "...SSSHBBBSSS...",
            "...SSSHBBBSSS...",
            "....SSHHHHSS....",
            ".....SSHHSS.....",
            "......SSSS......",
            ".....kGGGGk.....",
            "....kGGGGGGk....",
            "...kGGGGGGGGk...",
            "...kGGGGGGGGk...",
            "....kGGGGGGk....",
            ".....kGGGGk.....",
            "......kGGk......",
            ".......bB.......",
            "......bBbB......",
            ".....bBbBbB.....",
            "......bBbB......",
            ".......bB.......",
        ],
    ],
    "dooku": [
        [
            "......WWWW......",
            ".....WWWWWW.....",
            "....WWWWWWWW....",
            "...WWWWWWWWWW...",
            "...WWwWWwWWWW...",
            "....WWWWWWWW....",
            ".....WWWWWW.....",
            "......WWWW......",
            ".....kKKKKk.....",
            "....kKKKKKKk....",
            "...kKKKKKKKKk...",
            "...kKKKKKKKKk...",
            "...kKKKKKKKKk...",
            "....kKKKKKKk....",
            ".....kKKKKk.....",
            "......kKKk......",
            ".......RR.......",
            "......RRrR......",
            ".....RRrRRR.....",
            "......RRrR......",
            ".......RR.......",
        ],
        [
            "......WWWW......",
            ".....WWWWWW.....",
            "....WWWWWWWW....",
            "...WWWWWWWWWW...",
            "...WWwWWwWWWW...",
            "....WWWWWWWW....",
            ".....WWWWWW.....",
            "......WWWW......",
            ".....kKKKKk.....",
            "....kKKKKKKk....",
            "...kKKKKKKKKk...",
            "...kKKKKKKKKk...",
            "...kKKKKKKKKk...",
            "....kKKKKKKk....",
            ".....kKKKKk.....",
            "......kKKk......",
            "......RRrR......",
            ".....RRrRRR.....",
            "....RRrRRrRR....",
            ".....RRrRRR.....",
            "......RRrR......",
        ],
        [
            "......WWWW......",
            ".....WWWWWW.....",
            "....WWWWWWWW....",
            "...WWWWWWWWWW...",
            "...WWwWWwWWWW...",
            "....WWWWWWWW....",
            ".....WWWWWW.....",
            "......WWWW......",
            ".....kKKKKk.....",
            "....kKKKKKKk....",
            "...kKKKKKKKKk...",
            "...kKKKKKKKKk...",
            "...kKKKKKKKKk...",
            "....kKKKKKKk....",
            ".....kKKKKk.....",
            "......kKKk......",
            "....RRrRRrRR....",
            "...RRrRRrRRrR...",
            "..RRrRRrRRrRR...",
            "...RRrRRrRRrR...",
            "....RRrRRrRR....",
        ],
        [
            "......WWWW......",
            ".....WWWWWW.....",
            "....WWWWWWWW....",
            "...WWWWWWWWWW...",
            "...WWwWWwWWWW...",
            "....WWWWWWWW....",
            ".....WWWWWW.....",
            "......WWWW......",
            ".....kKKKKk.....",
            "....kKKKKKKk....",
            "...kKKKKKKKKk...",
            "...kKKKKKKKKk...",
            "...kKKKKKKKKk...",
            "....kKKKKKKk....",
            ".....kKKKKk.....",
            "......kKKk......",
            ".......RR.......",
            "......RRrR......",
            ".....RRrRRR.....",
            "......RRrR......",
            ".......RR.......",
        ],
    ],
}


def sprite_size(character: str) -> tuple[int, int]:
    frame = SPRITES[character][0]
    return len(frame[0]), len(frame)


def asset_path(character: str, frame_idx: int) -> Path:
    return ASSETS_DIR / f"{character}_{frame_idx}.png"


def assets_available() -> bool:
    return asset_path("vader", 0).exists()


def image_pixel_size(character: str) -> tuple[int, int]:
    path = asset_path(character, 0)
    if path.exists():
        from PIL import Image

        with Image.open(path) as img:
            return img.size
    w, h = sprite_size(character)
    return w * PIXEL, h * PIXEL


def draw_sprite(canvas, character: str, frame_idx: int, ox: int, oy: int, bob: int = 0) -> None:
    palette = PALETTES[character]
    grid = SPRITES[character][frame_idx % len(SPRITES[character])]
    oy += bob
    scale = PIXEL
    for row, line in enumerate(grid):
        for col, ch in enumerate(line):
            color = palette.get(ch, "")
            if not color:
                continue
            x1 = ox + col * scale
            y1 = oy + row * scale
            canvas.create_rectangle(
                x1, y1, x1 + scale, y1 + scale, fill=color, outline=color
            )


def draw_glow(canvas, ox: int, oy: int, w: int, h: int, color: str, frame: int) -> None:
    canvas.create_oval(
        ox - 6, oy - 6, ox + w + 6, oy + h + 6,
        fill="", outline=color, width=2,
    )